@ECHO OFF
CD %PROGRAMFILES%\SDL
START C:\"Program Files"\SDL\SDL-SL\SDLSL.exe
set /p STEAMLOCATION=<STEAM.LOCATION
set /p CLOSEDLOCATION=<CLOSED.LOCATION
START /WAIT %STEAMLOCATION% -noverifyfiles -gamepadui
START %CLOSEDLOCATION%