@ECHO OFF
set /p SDL-LOCATION=<C:\"Steam Deck Launcher"
CD %SDL-Location%
set /p STEAMLOCATION=<STEAM.LOCATION
START /WAIT %STEAMLOCATION% -noverifyfiles -gamepadui
set /p CLOSEDLOCATION=<CLOSED.LOCATION
START %CLOSEDLOCATION%
EXIT